Kunena/Kunena-Forum

components/com_kunena/site/template/crypsis/layouts/topic/row/category.php
=> [K3.1] Crypsis : Add class="kcontenttablespacer" to spacers after Sticky #2514

components/com_kunena/site/controller/widget/announcement/display.php
also excluded on profile and on announcement
=> [K3.1] Crypsis: Hide announcement on new topic page #2704

components/com_kunena/site/template/crypsis/layouts/user/item/summary/default.php
=> [3.1] Crypsis : Show E-mail = No has no effect. The address is always public #2742 

components/com_kunena/site/template/blue_eagle/css/kunena.forum.css, components/com_kunena/site/template/blue_eagle/css/kunena.forum.rtl.css
Fixed the date, and other small issue's
=> [K3.0] RTL: fixes

components/com_kunena/site/views/user/view.html.php
=> [K3.0.7] Menu item Profile > Use Integration = No: Click in Kunena profile on edit gives a redirect to the CP Profile #1835

components/com_kunena/site/template/blue_eagle/css/kunena.forum.css
=> [3.0] Blue eagle: Css update

README.md, pkg_kunena.xml
@mahagr could you do the last steps
=> Kunena 3.0.7 Release

components/com_kunena/site/views/topics/view.feed.php
- by posts
- by recent messages
=> [3.1] Rss: Hide message if teaser is enabled

components/com_kunena/site/views/topic/view.html.php, libraries/kunena/forum/message/message.php, libraries/kunena/view.php
this has to been done already a year ago. but not included in the core.
Several users are doing this after each version, we should include this.
=> [K3.0.8] Improve SEO

components/com_kunena/site/template/crypsis/layouts/category/index/default.php, components/com_kunena/site/template/crypsis/layouts/topic/edit/default.php, components/com_kunena/site/template/crypsis/layouts/topic/edit/editor/default.php, components/com_kunena/site/template/crypsis/less/editor.less, components/com_kunena/site/template/crypsis/media/js/upload.main.js
- Kunena#2296
- Uploader
- html index, alert
=> [K3.1] Crypsis: fix some issues

components/com_kunena/site/template/blue_eagle/css/kunena.default.css, components/com_kunena/site/template/blue_eagle/html/category/list_embed.php, components/com_kunena/site/template/blue_eagle/html/statistics/default.php, components/com_kunena/site/template/blue_eagle/html/topic/default.php, components/com_kunena/site/template/blue_eagle/html/user/list.php
- Topics
- Sub Category
- Userlist
- Statistics
=> Improve SEO part 2

components/com_kunena/admin/template/joomla25/categories/edit.php, components/com_kunena/admin/template/joomla30/categories/edit.php
Now you can order the topics by
- Last Post Time
- Topic Creation Time
- Alphabetical order
Feature allows you to create Category Aliases,
=> [K3.1] Feature: Add Topic Ordering and Channels

components/com_kunena/site/controllers/user.php, components/com_kunena/site/views/common/view.html.php
https://github.com/Kunena/Kunena-Forum/issues/2835
=> [K3.0.8] Allow Guests to see Userlist = No - but guests find the userlist by entering the URL #2835

components/com_kunena/admin/language/en-GB/en-GB.com_kunena.models.ini, components/com_kunena/admin/models/config.php, libraries/kunena/forum/message/message.php
https://github.com/Kunena/Kunena-Forum/issues/2837
=> [K3.1] User Edits : We should add a third option #2837 

components/com_kunena/admin/models/config.php, components/com_kunena/admin/template/joomla25/config/default.php, components/com_kunena/admin/template/joomla30/config/default.php, libraries/kunena/config.php
Remove option. Now its just real or username.
=> [master][3.0.7] Userlist Settings | Show Real Name = Yes has no effect #2526

components/com_kunena/admin/install/install.xml, components/com_kunena/admin/install/kunena.install.upgrade.xml, components/com_kunena/admin/install/sql/install/mysql/create_tables.utf8.sql, components/com_kunena/admin/install/sql/updates/mysql/4.0.0-2015-03-26.sql, components/com_kunena/admin/language/en-GB/en-GB.com_kunena.views.ini, components/com_kunena/admin/template/joomla25/categories/edit.php, components/com_kunena/admin/template/joomla30/categories/edit.php, components/com_kunena/site/template/blue_eagle/css/kunena.default.css, components/com_kunena/site/template/blue_eagle/html/category/list_embed.php, components/com_kunena/site/template/crypsis/layouts/category/index/default.php, components/com_kunena/site/template/crypsis/less/general.less, libraries/kunena/forum/category/category.php, libraries/kunena/tables/kunenacategories.php, pkg_kunena.xml
Instead of uploader, we should use input because now you can use icomoon
icons, or own classes
=> Add category icon upload and gallery #41

libraries/kunena/forum/message/message.php
https://github.com/Kunena/Kunena-Forum/issues/2692
=> [K3.0.9] Public write access and hidden text for guests #2692

components/com_kunena/site/template/crypsis/layouts/message/list/default.php, components/com_kunena/site/views/topics/tmpl/user.xml
ps, change setting on kunenmenu, select item,  main settings tab, change
filter to global
=> [K4.0] Crypsis: Time periods does not work (Recent Posts etc..) It goes back to All. #2854

libraries/kunena/bbcode/bbcode.php
I'am still experiencing this issue with last build
=> Issue when on reply when you have in previous message a confidential #3005

libraries/kunena/attachment/attachment.php
=> [4.0] Blue Eagle: Error Uploading Attachment (such as pdf, zip et..)

components/com_kunena/site/template/crypsis/layouts/user/item/summary/default.php, components/com_kunena/site/template/crypsis/layouts/widget/login/logout/default.php
See : http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/132845-timezone-issue?start=10#164732
=> Timezone Issue in profile summary and logout box

components/com_kunena/admin/controllers/templates.php, components/com_kunena/admin/language/en-GB/en-GB.com_kunena.libraries.ini, components/com_kunena/admin/language/en-GB/en-GB.com_kunena.views.ini, components/com_kunena/admin/models/templates.php, components/com_kunena/admin/template/joomla30/templates/chooseless.php, components/com_kunena/admin/template/joomla30/templates/editless.php, components/com_kunena/admin/views/templates/view.html.php, components/com_kunena/site/template/blue_eagle/template.php, components/com_kunena/site/template/crypsis/template.php
=> [K4.0] Backend: Edit less

components/com_kunena/site/template/crypsis/layouts/category/index/default.php, components/com_kunena/site/template/crypsis/layouts/user/profile/default.php, components/com_kunena/site/template/crypsis/layouts/user/profile/horizontal.php, components/com_kunena/site/template/crypsis/layouts/widget/login/login/default.php, components/com_kunena/site/template/crypsis/layouts/widget/login/logout/default.php
kunena_profile_horizontal
kunena_profile_default
kunena_logout
kunena_login
=> [K4.0] Crypsis add more module positions

libraries/kunena/spam/recaptcha.php
Users" setting and you haven't filled private/public key so you can't reply
This issue happens with blue eagle
=> If the user isn't a mod and has less posts than "CAPTCHA Challenge for

components/com_kunena/site/views/search/view.html.php
Because now the title is trimmed.
=> [K4.0] Disable highlight blue eagle.

components/com_kunena/site/models/topic.php, libraries/kunena/user/user.php
continue to see Oldest Post First #3133
=> [K4.0] Post ordering: When global setting is Newest Post First, guests

components/com_kunena/admin/controllers/categories.php
We still need to fix the Jrequest from post
=> [k4.1] Update save

components/com_kunena/site/controllers/user.php, components/com_kunena/site/language/en-GB/en-GB.com_kunena.ini, libraries/kunena/upload/upload.php
Try to upload an attachment with blue eagle and upload a new avatar because this two parts use the same code
=> [K4.0] Blue Eagle: Image upload works only with Max. Avatar File Size #3212

components/com_kunena/site/template/blue_eagle/html/category/default_row.php, components/com_kunena/site/template/blue_eagle/html/category/list_embed.php, components/com_kunena/site/template/blue_eagle/html/category/user_row.php, components/com_kunena/site/template/blue_eagle/html/search/default_row.php, components/com_kunena/site/template/blue_eagle/html/topic/default_profile_horizontal.php, components/com_kunena/site/template/blue_eagle/html/topic/default_profile_vertical.php, components/com_kunena/site/template/blue_eagle/html/topics/default_row.php, components/com_kunena/site/template/blue_eagle/html/topics/posts_row.php, components/com_kunena/site/template/blue_eagle/html/topics/user_row.php, components/com_kunena/site/template/crypsis/layouts/category/index/default.php, components/com_kunena/site/template/crypsis/layouts/message/row/default.php, components/com_kunena/site/template/crypsis/layouts/search/results/row/default.php, components/com_kunena/site/template/crypsis/layouts/topic/row/category.php, components/com_kunena/site/template/crypsis/layouts/topic/row/default.php, components/com_kunena/site/template/crypsis/layouts/topic/row/user.php, components/com_kunena/site/template/crypsisb3/layouts/category/index/default.php, components/com_kunena/site/template/crypsisb3/layouts/message/row/default.php, components/com_kunena/site/template/crypsisb3/layouts/search/results/row/default.php, components/com_kunena/site/template/crypsisb3/layouts/topic/row/category.php, components/com_kunena/site/template/crypsisb3/layouts/topic/row/default.php, components/com_kunena/site/template/crypsisb3/layouts/topic/row/user.php, libraries/kunena/user/user.php
=> [develop] [4.0] Category moderators are displayed as moderator in all

components/com_kunena/admin/install/install.xml, components/com_kunena/admin/install/kunena.install.upgrade.xml, components/com_kunena/admin/install/sql/install/mysql/create_tables.utf8.sql, components/com_kunena/admin/install/sql/updates/mysql/4.0.2-2015-06-18.sql, pkg_kunena.xml
=> [K4.0] Update sql to support more characters

components/com_kunena/site/language/en-GB/en-GB.kunena_tmpl_crypsis.ini, components/com_kunena/site/template/crypsis/layouts/topic/edit/default.php, components/com_kunena/site/template/crypsis/layouts/topic/edit/editor/default.php, components/com_kunena/site/template/crypsis/media/js/edit.js
complete post for each letter. #3229
=> [K4.0] Crypsis : To write is a problem with Preview. It loads the complete post for each letter. #3229

components/com_kunena/site/template/system/layouts/email/report/default.php, components/com_kunena/site/template/system/layouts/email/subscription/default.php, components/com_kunena/site/template/system/layouts/email/subscription/moderator.php
See: http://www.kunena.org/forum/k-3-0-general-questions/132085-new-post-email-notification-url-broken?start=40#166352
=> Add email layouts under system for url issue with blue eagle

components/com_kunena/site/template/crypsis/layouts/topic/edit/default.php, components/com_kunena/site/template/crypsis/media/js/poll.js, components/com_kunena/site/template/crypsisb3/layouts/topic/edit/default.php, components/com_kunena/site/template/crypsisb3/media/js/poll.js
=>  Crypsis: Edit poll is not possible (it missing the poll symbol in the

components/com_kunena/site/template/crypsis/layouts/topic/edit/default.php, components/com_kunena/site/template/crypsis/layouts/topic/edit/editor/default.php, components/com_kunena/site/template/crypsis/less/general.less
=> Crypsis: Html fixes
